FROM eclipse-temurin:21-jdk AS build

WORKDIR /app
COPY gradlew settings.gradle build.gradle ./
COPY gradle/ gradle/
COPY flink/ flink/

RUN chmod +x gradlew && ./gradlew :flink:collector:installDist --no-daemon

FROM eclipse-temurin:17-jre

WORKDIR /app
COPY --from=build /app/flink/collector/build/install/collector/ ./

ENTRYPOINT ["bin/collector"]
